version: '3.9'
networks:
  network:
    driver: bridge

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready","-d","postgres","-U","postgres" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks:
      - network
    restart: always

  app:
#    build: .
    image: kerimovikh/nexign-billing:latest
    container_name: app
    restart: always
    volumes:
      - ./report:/opt/app/report
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy
