spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: default
    show-sql: true
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 50
        order_updates: true

  flyway:
    baseline-on-migrate: true

jwt:
  secret:
    key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970